FROM ubuntu:22.04

LABEL name="cdm-vcontainer" \
      maintainers="Cuong. Duong Manh" \
      email="cuongdm8499@gmail.com"
      
RUN apt update && apt install -y traceroute telnet curl dnsutils

CMD ["/bin/bash"]

